spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reserve
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.web: DEBUG