spring:
  datasource:
    hikari:
      leak-detection-threshold: 2000

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.web: DEBUG
